# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rov_canbus_pkg/joystick.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rov_canbus_pkg.msg

class joystick(genpy.Message):
  _md5sum = "e64b1b8f03464111f861d5d5c0e8e7e1"
  _type = "rov_canbus_pkg/joystick"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """my_thruster thruster
================================================================================
MSG: rov_canbus_pkg/my_thruster
float32 bldc
float32 green_1
float32 green_2
float32 yellow_1
float32 yellow_2
float32 yellow_3"""
  __slots__ = ['thruster']
  _slot_types = ['rov_canbus_pkg/my_thruster']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       thruster

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(joystick, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.thruster is None:
        self.thruster = rov_canbus_pkg.msg.my_thruster()
    else:
      self.thruster = rov_canbus_pkg.msg.my_thruster()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.thruster.bldc, _x.thruster.green_1, _x.thruster.green_2, _x.thruster.yellow_1, _x.thruster.yellow_2, _x.thruster.yellow_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.thruster is None:
        self.thruster = rov_canbus_pkg.msg.my_thruster()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.thruster.bldc, _x.thruster.green_1, _x.thruster.green_2, _x.thruster.yellow_1, _x.thruster.yellow_2, _x.thruster.yellow_3,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.thruster.bldc, _x.thruster.green_1, _x.thruster.green_2, _x.thruster.yellow_1, _x.thruster.yellow_2, _x.thruster.yellow_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.thruster is None:
        self.thruster = rov_canbus_pkg.msg.my_thruster()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.thruster.bldc, _x.thruster.green_1, _x.thruster.green_2, _x.thruster.yellow_1, _x.thruster.yellow_2, _x.thruster.yellow_3,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
