# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rov_canbus_pkg/my_sensors.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rov_canbus_pkg.msg

class my_sensors(genpy.Message):
  _md5sum = "e69800ec6584751e8ef4cbb24d578d8c"
  _type = "rov_canbus_pkg/my_sensors"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """imu_data imu
float32 depth
================================================================================
MSG: rov_canbus_pkg/imu_data
float32 roll
float32 pitch
float32 yaw"""
  __slots__ = ['imu','depth']
  _slot_types = ['rov_canbus_pkg/imu_data','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       imu,depth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(my_sensors, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.imu is None:
        self.imu = rov_canbus_pkg.msg.imu_data()
      if self.depth is None:
        self.depth = 0.
    else:
      self.imu = rov_canbus_pkg.msg.imu_data()
      self.depth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.imu.roll, _x.imu.pitch, _x.imu.yaw, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.imu is None:
        self.imu = rov_canbus_pkg.msg.imu_data()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.imu.roll, _x.imu.pitch, _x.imu.yaw, _x.depth,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.imu.roll, _x.imu.pitch, _x.imu.yaw, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.imu is None:
        self.imu = rov_canbus_pkg.msg.imu_data()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.imu.roll, _x.imu.pitch, _x.imu.yaw, _x.depth,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
