// Generated by gencpp from file rov_canbus_pkg/camera.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_CAMERA_H
#define ROV_CANBUS_PKG_MESSAGE_CAMERA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rov_canbus_pkg/m_setup_camera.h>

namespace rov_canbus_pkg
{
template <class ContainerAllocator>
struct camera_
{
  typedef camera_<ContainerAllocator> Type;

  camera_()
    : camera()  {
    }
  camera_(const ContainerAllocator& _alloc)
    : camera(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rov_canbus_pkg::m_setup_camera_<ContainerAllocator>  _camera_type;
  _camera_type camera;





  typedef boost::shared_ptr< ::rov_canbus_pkg::camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_canbus_pkg::camera_<ContainerAllocator> const> ConstPtr;

}; // struct camera_

typedef ::rov_canbus_pkg::camera_<std::allocator<void> > camera;

typedef boost::shared_ptr< ::rov_canbus_pkg::camera > cameraPtr;
typedef boost::shared_ptr< ::rov_canbus_pkg::camera const> cameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_canbus_pkg::camera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_canbus_pkg::camera_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_canbus_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rov_canbus_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_canbus_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::camera_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_canbus_pkg::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdec6a66e2e4b31d3db7162f12cb9ca5";
  }

  static const char* value(const ::rov_canbus_pkg::camera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdec6a66e2e4b31dULL;
  static const uint64_t static_value2 = 0x3db7162f12cb9ca5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_canbus_pkg::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_canbus_pkg/camera";
  }

  static const char* value(const ::rov_canbus_pkg::camera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_canbus_pkg::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "m_setup_camera camera\n\
================================================================================\n\
MSG: rov_canbus_pkg/m_setup_camera\n\
uint8 camera_zoom\n\
uint8 camera_focus\n\
uint8 camera_bright\n\
";
  }

  static const char* value(const ::rov_canbus_pkg::camera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_canbus_pkg::camera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_canbus_pkg::camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_canbus_pkg::camera_<ContainerAllocator>& v)
  {
    s << indent << "camera: ";
    s << std::endl;
    Printer< ::rov_canbus_pkg::m_setup_camera_<ContainerAllocator> >::stream(s, indent + "  ", v.camera);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_CAMERA_H
