// Generated by gencpp from file rov_canbus_pkg/mode_control.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_MODE_CONTROL_H
#define ROV_CANBUS_PKG_MESSAGE_MODE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rov_canbus_pkg
{
template <class ContainerAllocator>
struct mode_control_
{
  typedef mode_control_<ContainerAllocator> Type;

  mode_control_()
    : manual(false)
    , auto(false)  {
    }
  mode_control_(const ContainerAllocator& _alloc)
    : manual(false)
    , auto(false)  {
  (void)_alloc;
    }



   typedef uint8_t _manual_type;
  _manual_type manual;

   typedef uint8_t _auto_type;
  _auto_type auto;





  typedef boost::shared_ptr< ::rov_canbus_pkg::mode_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_canbus_pkg::mode_control_<ContainerAllocator> const> ConstPtr;

}; // struct mode_control_

typedef ::rov_canbus_pkg::mode_control_<std::allocator<void> > mode_control;

typedef boost::shared_ptr< ::rov_canbus_pkg::mode_control > mode_controlPtr;
typedef boost::shared_ptr< ::rov_canbus_pkg::mode_control const> mode_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_canbus_pkg::mode_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_canbus_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rov_canbus_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_canbus_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::mode_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::mode_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::mode_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f01efd757ee8c9f69cd0dba342421f0";
  }

  static const char* value(const ::rov_canbus_pkg::mode_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f01efd757ee8c9fULL;
  static const uint64_t static_value2 = 0x69cd0dba342421f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_canbus_pkg/mode_control";
  }

  static const char* value(const ::rov_canbus_pkg::mode_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool manual\n\
bool auto\n\
";
  }

  static const char* value(const ::rov_canbus_pkg::mode_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.manual);
      stream.next(m.auto);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mode_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_canbus_pkg::mode_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_canbus_pkg::mode_control_<ContainerAllocator>& v)
  {
    s << indent << "manual: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manual);
    s << indent << "auto: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auto);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_MODE_CONTROL_H
