// Generated by gencpp from file rov_canbus_pkg/my_pid.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_MY_PID_H
#define ROV_CANBUS_PKG_MESSAGE_MY_PID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rov_canbus_pkg
{
template <class ContainerAllocator>
struct my_pid_
{
  typedef my_pid_<ContainerAllocator> Type;

  my_pid_()
    : Kp(0.0)
    , Ki(0.0)
    , Kd(0.0)  {
    }
  my_pid_(const ContainerAllocator& _alloc)
    : Kp(0.0)
    , Ki(0.0)
    , Kd(0.0)  {
  (void)_alloc;
    }



   typedef float _Kp_type;
  _Kp_type Kp;

   typedef float _Ki_type;
  _Ki_type Ki;

   typedef float _Kd_type;
  _Kd_type Kd;





  typedef boost::shared_ptr< ::rov_canbus_pkg::my_pid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_canbus_pkg::my_pid_<ContainerAllocator> const> ConstPtr;

}; // struct my_pid_

typedef ::rov_canbus_pkg::my_pid_<std::allocator<void> > my_pid;

typedef boost::shared_ptr< ::rov_canbus_pkg::my_pid > my_pidPtr;
typedef boost::shared_ptr< ::rov_canbus_pkg::my_pid const> my_pidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_canbus_pkg::my_pid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_canbus_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rov_canbus_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_canbus_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::my_pid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::my_pid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::my_pid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efa8beee6353230a5babb632ca65705b";
  }

  static const char* value(const ::rov_canbus_pkg::my_pid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefa8beee6353230aULL;
  static const uint64_t static_value2 = 0x5babb632ca65705bULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_canbus_pkg/my_pid";
  }

  static const char* value(const ::rov_canbus_pkg::my_pid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Kp\n\
float32 Ki\n\
float32 Kd\n\
";
  }

  static const char* value(const ::rov_canbus_pkg::my_pid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Kp);
      stream.next(m.Ki);
      stream.next(m.Kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_pid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_canbus_pkg::my_pid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_canbus_pkg::my_pid_<ContainerAllocator>& v)
  {
    s << indent << "Kp: ";
    Printer<float>::stream(s, indent + "  ", v.Kp);
    s << indent << "Ki: ";
    Printer<float>::stream(s, indent + "  ", v.Ki);
    s << indent << "Kd: ";
    Printer<float>::stream(s, indent + "  ", v.Kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_MY_PID_H
