// Generated by gencpp from file rov_canbus_pkg/my_robot_arm.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_MY_ROBOT_ARM_H
#define ROV_CANBUS_PKG_MESSAGE_MY_ROBOT_ARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rov_canbus_pkg
{
template <class ContainerAllocator>
struct my_robot_arm_
{
  typedef my_robot_arm_<ContainerAllocator> Type;

  my_robot_arm_()
    : robot_arm_open(0)
    , robot_arm_close(0)
    , robot_arm_stop(0)  {
    }
  my_robot_arm_(const ContainerAllocator& _alloc)
    : robot_arm_open(0)
    , robot_arm_close(0)
    , robot_arm_stop(0)  {
  (void)_alloc;
    }



   typedef uint8_t _robot_arm_open_type;
  _robot_arm_open_type robot_arm_open;

   typedef uint8_t _robot_arm_close_type;
  _robot_arm_close_type robot_arm_close;

   typedef uint8_t _robot_arm_stop_type;
  _robot_arm_stop_type robot_arm_stop;





  typedef boost::shared_ptr< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> const> ConstPtr;

}; // struct my_robot_arm_

typedef ::rov_canbus_pkg::my_robot_arm_<std::allocator<void> > my_robot_arm;

typedef boost::shared_ptr< ::rov_canbus_pkg::my_robot_arm > my_robot_armPtr;
typedef boost::shared_ptr< ::rov_canbus_pkg::my_robot_arm const> my_robot_armConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_canbus_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rov_canbus_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_canbus_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc441effc562f63bdb89f9392fe90557";
  }

  static const char* value(const ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc441effc562f63bULL;
  static const uint64_t static_value2 = 0xdb89f9392fe90557ULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_canbus_pkg/my_robot_arm";
  }

  static const char* value(const ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 robot_arm_open\n\
uint8 robot_arm_close\n\
uint8 robot_arm_stop\n\
";
  }

  static const char* value(const ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_arm_open);
      stream.next(m.robot_arm_close);
      stream.next(m.robot_arm_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_robot_arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_canbus_pkg::my_robot_arm_<ContainerAllocator>& v)
  {
    s << indent << "robot_arm_open: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_arm_open);
    s << indent << "robot_arm_close: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_arm_close);
    s << indent << "robot_arm_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_arm_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_MY_ROBOT_ARM_H
