// Generated by gencpp from file rov_canbus_pkg/pid_control.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_PID_CONTROL_H
#define ROV_CANBUS_PKG_MESSAGE_PID_CONTROL_H

#include <ros/service_traits.h>


#include <rov_canbus_pkg/pid_controlRequest.h>
#include <rov_canbus_pkg/pid_controlResponse.h>


namespace rov_canbus_pkg
{

struct pid_control
{

typedef pid_controlRequest Request;
typedef pid_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pid_control
} // namespace rov_canbus_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rov_canbus_pkg::pid_control > {
  static const char* value()
  {
    return "f44360cec437240487440e29a8817f6f";
  }

  static const char* value(const ::rov_canbus_pkg::pid_control&) { return value(); }
};

template<>
struct DataType< ::rov_canbus_pkg::pid_control > {
  static const char* value()
  {
    return "rov_canbus_pkg/pid_control";
  }

  static const char* value(const ::rov_canbus_pkg::pid_control&) { return value(); }
};


// service_traits::MD5Sum< ::rov_canbus_pkg::pid_controlRequest> should match 
// service_traits::MD5Sum< ::rov_canbus_pkg::pid_control > 
template<>
struct MD5Sum< ::rov_canbus_pkg::pid_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rov_canbus_pkg::pid_control >::value();
  }
  static const char* value(const ::rov_canbus_pkg::pid_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rov_canbus_pkg::pid_controlRequest> should match 
// service_traits::DataType< ::rov_canbus_pkg::pid_control > 
template<>
struct DataType< ::rov_canbus_pkg::pid_controlRequest>
{
  static const char* value()
  {
    return DataType< ::rov_canbus_pkg::pid_control >::value();
  }
  static const char* value(const ::rov_canbus_pkg::pid_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rov_canbus_pkg::pid_controlResponse> should match 
// service_traits::MD5Sum< ::rov_canbus_pkg::pid_control > 
template<>
struct MD5Sum< ::rov_canbus_pkg::pid_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rov_canbus_pkg::pid_control >::value();
  }
  static const char* value(const ::rov_canbus_pkg::pid_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rov_canbus_pkg::pid_controlResponse> should match 
// service_traits::DataType< ::rov_canbus_pkg::pid_control > 
template<>
struct DataType< ::rov_canbus_pkg::pid_controlResponse>
{
  static const char* value()
  {
    return DataType< ::rov_canbus_pkg::pid_control >::value();
  }
  static const char* value(const ::rov_canbus_pkg::pid_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_PID_CONTROL_H
