// Generated by gencpp from file rov_canbus_pkg/pid_controlResponse.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_PID_CONTROLRESPONSE_H
#define ROV_CANBUS_PKG_MESSAGE_PID_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rov_canbus_pkg
{
template <class ContainerAllocator>
struct pid_controlResponse_
{
  typedef pid_controlResponse_<ContainerAllocator> Type;

  pid_controlResponse_()
    : duty_cycle(0.0)  {
    }
  pid_controlResponse_(const ContainerAllocator& _alloc)
    : duty_cycle(0.0)  {
  (void)_alloc;
    }



   typedef float _duty_cycle_type;
  _duty_cycle_type duty_cycle;





  typedef boost::shared_ptr< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pid_controlResponse_

typedef ::rov_canbus_pkg::pid_controlResponse_<std::allocator<void> > pid_controlResponse;

typedef boost::shared_ptr< ::rov_canbus_pkg::pid_controlResponse > pid_controlResponsePtr;
typedef boost::shared_ptr< ::rov_canbus_pkg::pid_controlResponse const> pid_controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_canbus_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rov_canbus_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_canbus_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b1e8af79e9957aa39f0d7274f652afb";
  }

  static const char* value(const ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b1e8af79e9957aaULL;
  static const uint64_t static_value2 = 0x39f0d7274f652afbULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_canbus_pkg/pid_controlResponse";
  }

  static const char* value(const ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 duty_cycle\n\
";
  }

  static const char* value(const ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duty_cycle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_canbus_pkg::pid_controlResponse_<ContainerAllocator>& v)
  {
    s << indent << "duty_cycle: ";
    Printer<float>::stream(s, indent + "  ", v.duty_cycle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_PID_CONTROLRESPONSE_H
