// Generated by gencpp from file rov_canbus_pkg/rc_servo.msg
// DO NOT EDIT!


#ifndef ROV_CANBUS_PKG_MESSAGE_RC_SERVO_H
#define ROV_CANBUS_PKG_MESSAGE_RC_SERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rov_canbus_pkg
{
template <class ContainerAllocator>
struct rc_servo_
{
  typedef rc_servo_<ContainerAllocator> Type;

  rc_servo_()
    : rc_servo(0.0)  {
    }
  rc_servo_(const ContainerAllocator& _alloc)
    : rc_servo(0.0)  {
  (void)_alloc;
    }



   typedef float _rc_servo_type;
  _rc_servo_type rc_servo;





  typedef boost::shared_ptr< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> const> ConstPtr;

}; // struct rc_servo_

typedef ::rov_canbus_pkg::rc_servo_<std::allocator<void> > rc_servo;

typedef boost::shared_ptr< ::rov_canbus_pkg::rc_servo > rc_servoPtr;
typedef boost::shared_ptr< ::rov_canbus_pkg::rc_servo const> rc_servoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_canbus_pkg::rc_servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_canbus_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rov_canbus_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_canbus_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13e2266f041bc10419d9aec8eec4fdb8";
  }

  static const char* value(const ::rov_canbus_pkg::rc_servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13e2266f041bc104ULL;
  static const uint64_t static_value2 = 0x19d9aec8eec4fdb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_canbus_pkg/rc_servo";
  }

  static const char* value(const ::rov_canbus_pkg::rc_servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 rc_servo\n\
";
  }

  static const char* value(const ::rov_canbus_pkg::rc_servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rc_servo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rc_servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_canbus_pkg::rc_servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_canbus_pkg::rc_servo_<ContainerAllocator>& v)
  {
    s << indent << "rc_servo: ";
    Printer<float>::stream(s, indent + "  ", v.rc_servo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_CANBUS_PKG_MESSAGE_RC_SERVO_H
