// Generated by gencpp from file rov_rosbridge_pkg/joystick.msg
// DO NOT EDIT!


#ifndef ROV_ROSBRIDGE_PKG_MESSAGE_JOYSTICK_H
#define ROV_ROSBRIDGE_PKG_MESSAGE_JOYSTICK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rov_rosbridge_pkg/my_thruster.h>

namespace rov_rosbridge_pkg
{
template <class ContainerAllocator>
struct joystick_
{
  typedef joystick_<ContainerAllocator> Type;

  joystick_()
    : thruster()  {
    }
  joystick_(const ContainerAllocator& _alloc)
    : thruster(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rov_rosbridge_pkg::my_thruster_<ContainerAllocator>  _thruster_type;
  _thruster_type thruster;





  typedef boost::shared_ptr< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> const> ConstPtr;

}; // struct joystick_

typedef ::rov_rosbridge_pkg::joystick_<std::allocator<void> > joystick;

typedef boost::shared_ptr< ::rov_rosbridge_pkg::joystick > joystickPtr;
typedef boost::shared_ptr< ::rov_rosbridge_pkg::joystick const> joystickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rov_rosbridge_pkg::joystick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rov_rosbridge_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rov_rosbridge_pkg': ['/home/ubuntu/ros_catkin_ws_rov/src/rov_rosbridge_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "366ba66c658c6e322e99dac7f045747d";
  }

  static const char* value(const ::rov_rosbridge_pkg::joystick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x366ba66c658c6e32ULL;
  static const uint64_t static_value2 = 0x2e99dac7f045747dULL;
};

template<class ContainerAllocator>
struct DataType< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rov_rosbridge_pkg/joystick";
  }

  static const char* value(const ::rov_rosbridge_pkg::joystick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_thruster thruster\n\
================================================================================\n\
MSG: rov_rosbridge_pkg/my_thruster\n\
float64 bldc\n\
float64 green_1\n\
float64 green_2\n\
float64 yellow_1\n\
float64 yellow_2\n\
float64 yellow_3\n\
";
  }

  static const char* value(const ::rov_rosbridge_pkg::joystick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thruster);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joystick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rov_rosbridge_pkg::joystick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rov_rosbridge_pkg::joystick_<ContainerAllocator>& v)
  {
    s << indent << "thruster: ";
    s << std::endl;
    Printer< ::rov_rosbridge_pkg::my_thruster_<ContainerAllocator> >::stream(s, indent + "  ", v.thruster);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROV_ROSBRIDGE_PKG_MESSAGE_JOYSTICK_H
